server:
  port: 8085
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

spring:
  application.name: EsServiceAndAdmin

logging:
  config: classpath:log4j2.yml

  #cloud.consul:
   #host: localhost
    #port: 8500
  #cloud:
    #consul:
      #discovery:
        #service-name: esService
        #设置不需要注册到 consul 中
        #register : false
