spring:
  # 缓存类型切换，本项目使用redis
  cache:
    type: redis
  ehcache:
    config: classpath:blog-ehcache.xml
  redis:
    host: 120.79.212.45
    password: kiwipeach
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 5000ms
    port: 6379
    database: 0
